# Generated by Django 4.0.6 on 2024-05-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_subjectmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_age',
        ),
    ]
