# Generated by Django 5.1.6 on 2025-02-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_remove_receipe_receipe_image_receipe_receipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_view_count',
        ),
    ]
